#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'rubocop_pr'
require 'benchmark'

cli = RubocopPr::CLI.new(ARGV)
result = 0

time = Benchmark.realtime do
  result = cli.run!
end

puts "Finished in #{time} seconds" if cli.options[:debug]
exit result
