#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'rubopop'
require 'benchmark'

cli = Rubopop::CLI.new
result = 0

time = Benchmark.realtime do
  result = cli.run(ARGV)
end

puts "Finished in #{time} seconds" if cli.options[:debug]
exit result
