#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'rubocop_on_github'
require 'benchmark'

cli = RubocopOnGithub::CLI.new
result = 0

time = Benchmark.realtime do
  result = cli.run
end

puts "Finished in #{time} seconds" if cli.options[:debug]
exit result
